version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - ACCOUNT=${ACCOUNT}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PORT=3001
    volumes:
      - ./ai:/app/ai
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=greencredit

volumes:
  mongo_data:
