version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    volumes:
      - ./ai:/app/ai
      - ./backend:/app/backend
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/greencredit
      - PORT=3001

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=greencredit

volumes:
  mongo_data:
